on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: kubercont.azurecr.io
        username: ${{ secrets.acr_kubercont_username }}
        password: ${{ secrets.acr_kubercont_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t kubercont.azurecr.io/myakscluster:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push kubercont.azurecr.io/myakscluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_myakscluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep myaksclustera230 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace myaksclustera230`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: myaksclustera230
        container-registry-url: kubercont.azurecr.io
        container-registry-username: ${{ secrets.acr_kubercont_username }}
        container-registry-password: ${{ secrets.acr_kubercont_password }}
        secret-name: myaksclusterdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: myaksclustera230
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          kubercont.azurecr.io/myakscluster:${{ github.sha }}
        imagepullsecrets: |
          myaksclusterdockerauth
